tunnel: b1c04110-a41a-4723-980f-15e00fd39aeb
credentials-file: ./secrets/cloudflare-credentials.json
ingress:
  - hostname: booth1.magicmoment.co.in
    service: http://localhost:3000
  - service: http_status:404
